# Generated by Django 3.1.5 on 2021-01-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_book"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="titre",
            new_name="title",
        ),
    ]
