# Generated by Django 3.1.5 on 2021-01-17 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_init_model_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_edition',
            field=models.DateField(default=datetime.datetime(2021, 1, 17, 20, 58, 5, 817822), verbose_name="date d'édition"),
        ),
    ]
