# Generated by Django 3.1.5 on 2021-05-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_categoryutils_imageutils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageutils',
            name='image',
            field=models.ImageField(upload_to='carousel'),
        ),
    ]
