# Generated by Django 3.1.5 on 2021-05-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210523_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageutils',
            name='image',
            field=models.ImageField(blank=True, upload_to='carousel'),
        ),
    ]
