# Generated by Django 3.1.5 on 2021-05-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210523_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageutils',
            name='image',
            field=models.FileField(blank=True, upload_to='carousel'),
        ),
    ]
