# Generated by Django 3.1.5 on 2021-05-29 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210524_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comments',
        ),
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.comment', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='book',
            name='likes',
            field=models.ManyToManyField(blank=True, to='core.Likes', verbose_name='Likes'),
        ),
    ]
