# Generated by Django 3.1.5 on 2021-05-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210529_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ontop',
            field=models.BooleanField(default=False),
        ),
    ]
