# Generated by Django 3.1.5 on 2021-06-09 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210609_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
