# Generated by Django 3.1.5 on 2021-06-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210610_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ontop',
            field=models.BooleanField(default=False),
        ),
    ]
