# Generated by Django 3.1.5 on 2021-07-29 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_utilisateur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'verbose_name': 'Utilisateur'},
        ),
    ]
