# Generated by Django 3.1.5 on 2021-07-29 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
