# Generated by Django 3.1.5 on 2021-08-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_book_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, to='core.Likes', verbose_name='Likes'),
        ),
    ]
