# Generated by Django 3.1.5 on 2021-09-22 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.utilisateur'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='illustration',
            field=models.ImageField(null=True, upload_to=None, verbose_name='illustration'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='likes',
            field=models.ManyToManyField(blank=True, to='core.Likes', verbose_name='Likes'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='ontop',
            field=models.BooleanField(default=False),
        ),
    ]
