# Generated by Django 3.1.5 on 2021-09-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210922_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='lien_debate',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Lien de vision'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='illustration'),
        ),
    ]
