# Generated by Django 3.1.5 on 2021-09-22 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210922_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
