# Generated by Django 3.1.5 on 2021-09-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_discussion_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to='core.Likes', verbose_name='Likes'),
        ),
    ]
