# Generated by Django 3.1.5 on 2021-09-27 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210927_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='book',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='likes',
        ),
        migrations.AddField(
            model_name='likes',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.article'),
        ),
        migrations.AddField(
            model_name='likes',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.book'),
        ),
        migrations.AddField(
            model_name='likes',
            name='discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.discussion'),
        ),
    ]
