# Generated by Django 3.1.5 on 2021-09-29 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_comment_date_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='number_likes',
        ),
    ]
