# Generated by Django 3.1.5 on 2021-10-05 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_likes_number_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='date_debut_reunion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discussion',
            name='date_fin_reunion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
