# Generated by Django 3.1.5 on 2021-10-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20211005_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
        migrations.AddField(
            model_name='book',
            name='ifile',
            field=models.FileField(null=True, upload_to='static'),
        ),
    ]
