# Generated by Django 3.1.5 on 2021-10-15 14:13

import core.model.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20211015_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ifile',
            field=models.FileField(null=True, upload_to='static', validators=[core.model.models.validate_file_size]),
        ),
    ]
