# Generated by Django 3.1.5 on 2021-10-15 14:21

import core.model.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20211015_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ifile',
            field=models.FileField(max_length=500, null=True, upload_to='static', validators=[core.model.models.validate_file_size]),
        ),
    ]
